import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const data=JSON.parse(fs.readFileSync(new URL('../src/data/asis.json',import.meta.url),'utf8'));
const get=id=>data.datasets.find(d=>d.id===id);
test('all published numeric records retain source, period, units and caution',()=>{
 assert.equal(new Set(data.datasets.map(d=>d.id)).size,data.datasets.length);
 for(const d of data.datasets){assert.ok(d.source.page>=1&&d.source.page<=97);assert.ok(d.source.table);assert.ok(d.source.institution);assert.ok(d.period);assert.ok(d.note);assert.ok(d.rows.length);for(const r of d.rows)for(const c of d.columns){assert.notEqual(r[c.key],undefined,`${d.id}/${c.key}`);if(c.numeric){assert.ok(Number.isFinite(r[c.key]));assert.ok(r[c.key]>=0);assert.ok(c.unit);}}}
});
test('province population and each life-course row reconcile for each period',()=>{for(const [y,total] of [[2023,44692],[2024,44219],[2025,43651]]){const rows=get('poblacion').rows.filter(r=>r.year===y);assert.equal(rows.length,13);assert.equal(rows.reduce((s,r)=>s+r.total,0),total);for(const r of rows)assert.equal(r.children+r.adolescents+r.youth+r.adults+r.older,r.total);}});
test('morbidity, mortality and life-course totals reconcile and sexes agree',()=>{for(const id of ['morbilidad','morbilidad-ninos','morbilidad-adolescentes','morbilidad-jovenes','morbilidad-adultos','morbilidad-mayores','morbilidad-distritos','mortalidad','mortalidad-distritos']){const d=get(id);const t=d.rows.at(-1);assert.equal(t.total,d.rows.slice(0,-1).reduce((s,r)=>s+r.total,0),id);for(const r of d.rows)assert.equal(r.female+r.male,r.total,id);}assert.equal(get('morbilidad').rows.at(-1).total,137266);assert.equal(get('mortalidad').rows.at(-1).total,204);});
test('service inventory reconciles without converting missing values into measurements',()=>{for(const id of ['infraestructura','internet','legal','computo'])assert.equal(get(id).rows.reduce((s,r)=>s+r.facilities,0),48);for(const r of get('infraestructura').rows)assert.equal(r.good+r.bad,r.facilities);for(const r of get('internet').rows)assert.equal(r.connected+r.disconnected,r.facilities);for(const r of get('legal').rows){assert.equal(r.legalYes+r.legalNo,r.facilities);assert.equal(r.titleYes+r.titleNo,r.facilities);}});
test('historical, inconsistent and ambiguous statistics stay clearly labelled',()=>{for(const d of data.datasets.filter(d=>d.module==='determinantes'))assert.equal(d.period,2017);assert.equal(get('emigracion').status,'warning');assert.ok(get('emigracion').rows.some(r=>r.value>100));assert.equal(get('densidad-estado').columns[1].unit,'unidad pendiente');assert.equal(get('dinamica').status,'warning');assert.equal(get('materno-perinatal').status,'warning');assert.ok(data.checks.every(c=>c.pass));});
test('official district geometries match names and UBIGEO, with no invented locations',()=>{const geo=JSON.parse(fs.readFileSync(new URL('../public/data/districts.geojson',import.meta.url),'utf8'));assert.equal(geo.features.length,13);for(const f of geo.features){const district=data.districts.find(d=>d.id===f.properties.IDDIST);assert.equal(f.properties.name,district.name);assert.ok(['Polygon','MultiPolygon'].includes(f.geometry.type));}assert.equal(data.geosource.publisher,'MINAM');assert.equal(data.geosource.crs,'EPSG:4326');});
test('public document index excludes clinical vignette and no private originals are packaged',()=>{const text=fs.readFileSync(new URL('../public/data/source-pages.json',import.meta.url),'utf8');for(const phrase of ['shock hipovolémico','ruptura uterina'])assert.ok(!text.includes(phrase));const files=fs.readdirSync(new URL('../public/documents/',import.meta.url));assert.deepEqual(files.sort(),['ASIS_SAN_MIGUEL_2025_PUBLICO.pdf','DESPLIEGUE.md','DIAGNOSTICO.md'].sort());});
