import {useEffect,useRef,useState} from 'react';
import {Download,Table2} from 'lucide-react';
import type {EChartsOption,ECharts} from 'echarts';
import {fmt,sourceUrl,type Dataset,type Row} from '../lib/data';
type Props={title:string;subtitle:string;d:Dataset;rows:Row[];category:string;values:{key:string;label:string}[];horizontal?:boolean;mode?:'bar'|'pyramid';height?:number;dark:boolean};
export default function Chart({title,subtitle,d,rows,category,values,horizontal=true,mode='bar',height=310,dark}:Props){
 const el=useRef<HTMLDivElement>(null),instance=useRef<ECharts|null>(null);const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[tabular,setTabular]=useState(false),[width,setWidth]=useState(600);
 useEffect(()=>{let alive=true;let observer:IntersectionObserver;let ro:ResizeObserver;
  const init=async()=>{try{const {init}=await import('../lib/chartRuntime');if(!alive||!el.current)return;instance.current=init(el.current);setWidth(el.current.clientWidth);setReady(true);ro=new ResizeObserver(()=>{instance.current?.resize();if(el.current&&el.current.clientWidth)setWidth(el.current.clientWidth);});ro.observe(el.current);}catch{if(alive)setFailed(true);}};
  observer=new IntersectionObserver(([e])=>{if(e.isIntersecting){observer.disconnect();void init();}},{rootMargin:'180px'});if(el.current)observer.observe(el.current);
  return()=>{alive=false;observer?.disconnect();ro?.disconnect();instance.current?.dispose();instance.current=null;};
 },[]);
 useEffect(()=>{if(!ready||!instance.current)return;
 const ink=dark?'#c7d5eb':'#52627d',line=dark?'#354565':'#e5ebf5';const cats=rows.map(r=>String(r[category]));const compact=width<500;
 const series=values.map((v,i)=>({name:v.label,type:'bar' as const,barMaxWidth:24,itemStyle:{color:(['good','connected','legalYes'].includes(v.key)?(dark?'#36cf86':'#00a859'):['bad','disconnected','legalNo'].includes(v.key)?(dark?'#f07c80':'#c43438'):(dark?['#52b7e7','#9dafec']:['#0087c6','#3c5395'])[i%2])},data:rows.map(r=>mode==='pyramid'&&i===0?-Number(r[v.key]):Number(r[v.key])),label:{show:values.length===1,position:'right' as const,color:ink,fontSize:12,formatter:(p:any)=>fmt(Math.abs(Number(p.value)))}}));
 const option:EChartsOption={backgroundColor:'transparent',animation:!matchMedia('(prefers-reduced-motion: reduce)').matches,animationDuration:450,textStyle:{fontFamily:'Inter, system-ui, sans-serif',color:ink},aria:{enabled:true},tooltip:{trigger:'axis',axisPointer:{type:'shadow'},valueFormatter:(v:any)=>String(fmt(Math.abs(Number(v))))},legend:{show:values.length>1,top:0,textStyle:{color:ink}},grid:{left:horizontal?'2%':'4%',right:values.length===1?64:25,top:values.length>1?38:12,bottom:12,containLabel:true},xAxis:horizontal?{type:'value',min:mode==='pyramid'?undefined:0,splitNumber:compact?2:5,axisLabel:{color:ink,hideOverlap:true,formatter:(v:number)=>compact&&Math.abs(v)>=1000?fmt(Math.abs(v)/1000)+' mil':String(fmt(Math.abs(v)))},splitLine:{lineStyle:{color:line}},axisLine:{show:true,lineStyle:{color:line}}}:{type:'category',data:cats,axisLabel:{color:ink},axisLine:{lineStyle:{color:line}}},yAxis:horizontal?{type:'category',data:cats,inverse:mode!=='pyramid',axisLabel:{color:ink,width:compact?135:170,overflow:'truncate',fontSize:12},axisTick:{show:false},axisLine:{lineStyle:{color:line}}}:{type:'value',min:0,axisLabel:{color:ink},splitLine:{lineStyle:{color:line}}},series};
 instance.current.setOption(option,true);
 },[ready,rows,values,category,horizontal,mode,dark,width]);
 const png=()=>{const url=instance.current?.getDataURL({type:'png',pixelRatio:2,backgroundColor:dark?'#182540':'#ffffff'});if(url){const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.width;c.height=img.height+160;const ctx=c.getContext('2d')!;ctx.fillStyle=dark?'#182540':'#ffffff';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle=dark?'#eef3fc':'#223257';ctx.font='bold 26px system-ui';ctx.fillText(title,30,40);ctx.font='20px system-ui';ctx.fillText(subtitle,30,75);ctx.drawImage(img,0,95);ctx.font='18px system-ui';ctx.fillText(`${d.source.institution} · ${d.source.table} · PDF p. ${d.source.page}`,30,c.height-25);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=d.id+'.png';a.click();};img.src=url;}};
 return <section className="panel chart-panel" aria-label={title}><div className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div><div className="icon-actions"><button className="icon-button" onClick={()=>setTabular(!tabular)} aria-label={'Ver tabla de '+title} aria-pressed={tabular}><Table2 size={17}/></button><button className="icon-button" onClick={png} disabled={!ready||failed} aria-label={'Descargar gráfico de '+title}><Download size={17}/></button></div></div><div ref={el} role="img" aria-label={`${title}. ${subtitle}. Datos disponibles en la tabla alternativa.`} style={{height}} hidden={tabular||failed}/>{!ready&&!failed&&!tabular&&<span className="loading-chart">Preparando visualización…</span>}{(tabular||failed)&&<div className="table-scroll"><table><caption className="sr-only">{title}</caption><thead><tr><th scope="col">Categoría</th>{values.map(v=><th key={v.key} scope="col">{v.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><th scope="row">{r[category]}</th>{values.map(v=><td key={v.key}>{fmt(r[v.key])}</td>)}</tr>)}</tbody></table>{failed&&<p>El gráfico no pudo cargarse. Puede consultar los mismos datos en esta tabla.</p>}</div>}<div className="chart-source"><a href={sourceUrl(d.source.page)} target="_blank" rel="noreferrer">{d.source.table} · PDF p. {d.source.page}</a><span>{d.source.institution}</span></div></section>;
}
