import {useEffect,useRef,useState} from 'react';
import {Maximize2} from 'lucide-react';
import 'leaflet/dist/leaflet.css';
import {dataset,detail,fmt,sourceUrl} from '../lib/data';
export default function TerritoryMap({dark,selected='all',onSelect,small=false}:{dark:boolean;selected?:string;onSelect?:(s:string)=>void;small?:boolean}){
 const el=useRef<HTMLDivElement>(null),map=useRef<any>(null),layers=useRef<any>(null),geometry=useRef<any>(null),L=useRef<any>(null);const [metric,setMetric]=useState('poblacion'),[status,setStatus]=useState('loading');
 const vals=metric==='poblacion'?detail(dataset(metric)).filter(r=>r.year===2025):detail(dataset(metric));const key=metric==='poblacion'?'total':metric==='infraestructura'?'bad':'value';const d=dataset(metric),max=Math.max(...vals.map(r=>Number(r[key])));
 useEffect(()=>{let alive=true;const init=async()=>{try{const leaflet=await import('leaflet');const res=await fetch(import.meta.env.BASE_URL+'data/districts.geojson');if(!res.ok)throw Error();const geo=await res.json();if(!alive||!el.current)return;L.current=leaflet;geometry.current=geo;map.current=leaflet.map(el.current,{scrollWheelZoom:false,attributionControl:true});map.current.attributionControl.addAttribution('<a href="https://geoservidorperu.minam.gob.pe/arcgis/rest/services/ServicioBase/MapServer/12">Límites referenciales: MINAM</a>');setStatus('ready');}catch{if(alive)setStatus('error');}};void init();return()=>{alive=false;map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(status!=='ready'||!map.current)return;layers.current?.remove();const leaf=L.current;
 const layer=leaf.geoJSON(geometry.current,{style:(f:any)=>{const row=vals.find(r=>r.district===f.properties.name);const value=Number(row?.[key]??0),v=value/max;return {color:dark?'#85bcc5':'#ffffff',weight:1.5,fillColor:v<.25?'#b6dee1':v<.5?'#6eb8c1':v<.75?'#258997':'#075764',fillOpacity:selected==='all'||selected===f.properties.name?.toString()?0.95:0.35};},onEachFeature:(f:any,l:any)=>{const row=vals.find(r=>r.district===f.properties.name);const box=document.createElement('div');const title=document.createElement('strong');title.textContent=f.properties.name;const text=document.createElement('p');text.textContent=fmt(Number(row?.[key]))+' '+(metric==='poblacion'?'habitantes':metric==='infraestructura'?'IPRESS en mal estado':'%')+' · '+(metric==='poblacion'?2025:d.period);box.append(title,text);const a=document.createElement('a');a.href=sourceUrl(d.source.page);a.target='_blank';a.rel='noreferrer';a.textContent=d.source.table+' · PDF p. '+d.source.page;box.append(a);l.bindPopup(box);l.bindTooltip(f.properties.name,{direction:'auto',sticky:true});l.on('click',()=>onSelect?.(f.properties.name));}}).addTo(map.current);layers.current=layer;map.current.fitBounds(layer.getBounds(),{padding:[small?15:30,15]});map.current.invalidateSize();if(selected!=='all')layer.eachLayer((l:any)=>{if(l.feature.properties.name===selected)l.openPopup();});
 },[status,metric,dark,selected]);
 return <section className="panel map-panel"><div className="panel-head"><div><h3>{small?'San Miguel, distrito a distrito':'Distribución territorial'}</h3><p>{metric==='poblacion'?'Población · habitantes · 2025':metric==='infraestructura'?'IPRESS en mal estado · unidades · 2025':d.title+' · % · 2017'}</p></div><button className="icon-button" aria-label="Mostrar todos los distritos en el mapa" onClick={()=>layers.current&&map.current.fitBounds(layers.current.getBounds())}><Maximize2 size={17}/></button></div>{!small&&<label className="map-selector">Indicador<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="poblacion">Población 2025</option><option value="agua">Acceso al agua 2017</option><option value="pobreza">Pobreza monetaria 2017</option><option value="infraestructura">Infraestructura 2025</option></select></label>}<div ref={el} className="map-canvas" style={{height:small?270:430}} aria-label="Mapa interactivo de los trece distritos de San Miguel"/>{status==='loading'&&<p className="map-status" role="status">Cargando cartografía oficial…</p>}{status==='error'&&<p role="alert">No se pudo cargar el mapa. Los datos territoriales están disponibles en las tablas.</p>}<div className="map-legend" aria-label={`Escala de color de cero a ${fmt(max)}; cuatro intervalos iguales`}><span>0</span>{[0,1,2,3].map(i=><i key={i} title={`${fmt(max*i/4)} a ${fmt(max*(i+1)/4)}`}/>)}<span>{fmt(max)}</span><span>Intervalos iguales</span></div><div className="chart-source"><a href={sourceUrl(d.source.page)} target="_blank" rel="noreferrer">{d.source.table} · PDF p. {d.source.page}</a><span>Cartografía: MINAM · EPSG:4326</span></div></section>;
}
